### ISSUE TITLE
Port data files to standardized output format (likely JSON)

### ISSUE THREAD

**Issue by zmorrell** [lanl-ansi/qc-applications#11]
We should port our outputs from our various resource estimation functions to write to a standardized data format for easier reading by other packages.  I propose JSON since it allows for easy addition of other data points in a heterogeneous manner, without being too bulky.

**Comment by ccoffrin** [comment]
JSON would be be good by me.  As long as the data you are storing is not too big, this is a good solution in my experince.

**Comment by JonhasSC** [comment]
Responded with PR https://github.com/lanl-ansi/qc-applications/pull/21
