### ISSUE TITLE
Clifford+T circuits not fully decomposed

### ISSUE THREAD

**Issue by tylerrleblond** [lanl-ansi/qc-applications#24]
Sample lines (279 - 292) from cube_circuits/cirq.ops.raw_types._InverseCompositeGate.cpt.qasm, which was output from MagneticLattices.ipynb:

`ry(pi*-0.5) q[1004];
u3(pi*0.5,0,pi*1.25) q[1300];
u3(pi*0.5,pi*1.0,pi*1.75) q[1004];
sx q[1300];
cx q[1300],q[1004];
rx(0) q[1300];
ry(pi*0.5) q[1004];
cx q[1004],q[1300];
sxdg q[1004];
s q[1004];
cx q[1300],q[1004];
u3(pi*0.5,pi*1.25,pi*1.0) q[1300];
u3(pi*0.5,pi*0.75,0) q[1004];
ry(pi*0.5) q[1004];`

Note: I have only seen this problem in circuits with the `cirq` prefix (and not those with the `pyLIQTR` prefix).

**Comment by ccoffrin** [comment]
Thanks for the heads up @tylerrleblond, we will look into it.

**Comment by JonhasSC** [comment]
An issue has been opened about this in pyLIQTR, https://github.com/isi-usc-edu/pyLIQTR/issues/11, which contains information on why this was happening

**Comment by JonhasSC** [comment]
Responded by https://github.com/lanl-ansi/qc-applications/pull/29. Closing this issue
