### ISSUE TITLE
Trotter unitary circuits missing from MagneticLattices.ipynb and RuClExample.ipynb

### ISSUE THREAD

**Issue by tylerrleblond** [lanl-ansi/qc-applications#25]
It seems that we obtain .qasm files for individual gates and/or their decompositions, but not the whole Trotter unitary.

Referring to the dev branch. I am unsure if this issue is present in main. 

Example:
![Screenshot 2024-04-05 at 11 08 26 AM](https://github.com/lanl-ansi/qc-applications/assets/12632882/7b8b2e3d-501d-4562-bdc8-c8652188d7e0)

**Comment by JonhasSC** [comment]
Fixed by the merging of PR https://github.com/lanl-ansi/qc-applications/pull/28
