### ISSUE TITLE
Generate extrapolation flags in metadata

### ISSUE THREAD

**Issue by zmorrell** [lanl-ansi/qc-applications#51]
Make sure that the proper flags, such as `is_extrapolated` are being raised in our resource estimates' metadata to make circuits that are generated easier to interpret/analyze.  Should include metadata as well about number of trotter steps/bits of precision as well.  This might be already done, but we should make sure it is done properly.

**Comment by gsgrattan** [comment]
Addressed in PR #61

**Comment by gsgrattan** [comment]
Addressed in PR #61
